ja:
    assignedissuescloud: "担当者毎へのチケットのリンク"
    customqueries: "カスタムクエリ"
    issuestoaccept: "担当するチケット"
    openversions: "作業中のバージョン"
    projectissuescloud: "プロジェクト毎へのチケットのリンク"
    recentstatuschanges: "最近の状態の変更"
    timeentryoverview: "時間入力の概要"
    userqueries: "ユーザクエリ"
    messagespostedinthelastweekonassignedprojects: "担当するプロジェクトの過去1週間の活動"
    recent_status_changes: Recent status changes (within 24 hours)
    label_issue_status_old: Old status
    assigned_issues_cloud: Assigned issues cloud
    project_issues_cloud: Project issues cloud
    custom_queries: "Custom queries"
    user_queries: "Issue status per user"
    label_user_queries: "Issue status per user"
    open_versions: "Open versions"
    time_entry_overview: "Time report summary"
    label_time_entry_overview: "Time report summary"
    issues_to_accept: "Open not assigned issues"
    label_reported_issues_to_accept: "Open not assigned issues"
    total: "Sum"
    messages_posted_in_the_last_week_on_assigned_projects: "Last forum messages"